In [43]:
import numpy as np # linear algebra
import pandas as pd

In [46]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [47]:
df=pd.read_csv('/content/fake_job_postings.csv.zip', index_col='job_id')
df.head()

,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
job_id,,,,,,,,,,,,,,,,,
1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0

In [48]:
df.shape

(17880, 17)

In [49]:
df.dtypes

title                  object
location               object
department             object
salary_range           object
company_profile        object
description            object
requirements           object
benefits               object
telecommuting           int64
has_company_logo        int64
has_questions           int64
employment_type        object
required_experience    object
required_education     object
industry               object
function               object
fraudulent              int64
dtype: object

In [50]:
df.duplicated().value_counts()

False    17599
True       281
Name: count, dtype: int64

In [51]:
df[df.fraudulent==0].duplicated().value_counts(normalize=True)

False    0.984072
True     0.015928
Name: proportion, dtype: float64

In [52]:
df[df.fraudulent==1].duplicated().value_counts(normalize=True)

False    0.988453
True     0.011547
Name: proportion, dtype: float64

In [53]:
df.drop_duplicates(inplace=True)

In [55]:
df.fraudulent.value_counts()

fraudulent
0    16743
1      856
Name: count, dtype: int64

In [56]:
df.fraudulent.value_counts(normalize=True)

fraudulent
0    0.951361
1    0.048639
Name: proportion, dtype: float64

In [57]:
df.describe(include='all')

,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
count,17599,17258,6271,2827,14317,17598,14950,10491,17599.000000,17599.000000,17599.000000,14171,10637,9590,12762,11236,17599.000000
unique,11231,3105,1337,874,1709,14801,11967,6204,NaN,NaN,NaN,5,7,13,131,37,NaN
top,English Teacher Abroad,"GB, LND, London",Sales,0-0,We help teachers get safe &amp; secure jobs ab...,"Play with kids, get paid for it Love travel? J...",University degree required. TEFL / TESOL / CEL...,See job description,NaN,NaN,NaN,Full-time,Mid-Senior level,Bachelor's Degree,Information Technology and Services,Information Technology,NaN
freq,309,718,541,141,723,376,407,723,NaN,NaN,NaN,11423,3768,5099,1711,1730,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.042843,0.794136,0.492017,NaN,NaN,NaN,NaN,NaN,0.048639
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.202510,0.404343,0.499950,NaN,NaN,NaN,NaN,NaN,0.215119
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,1.000000

In [58]:
df.isna().sum()

title                      0
location                 341
department             11328
salary_range           14772
company_profile         3282
description                1
requirements            2649
benefits                7108
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         3428
required_experience     6962
required_education      8009
industry                4837
function                6363
fraudulent                 0
dtype: int64

In [59]:
df_na=df.fillna('na')

In [61]:
real=df_na[df_na.fraudulent==0]
real.describe(include='all')

,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
count,16743,16743,16743,16743,16743,16743,16743,16743,16743.000000,16743.000000,16743.000000,16743,16743,16743,16743,16743,16743.0
unique,10730,2914,1270,829,1661,14171,11494,5903,NaN,NaN,NaN,6,8,14,131,38,NaN
top,English Teacher Abroad,"GB, LND, London",na,na,na,"Play with kids, get paid for it Love travel? J...",na,na,NaN,NaN,NaN,Full-time,na,na,na,na,NaN
freq,309,716,10804,14137,2702,376,2498,6750,NaN,NaN,NaN,10936,6535,7565,4567,6033,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.041211,0.817894,0.502299,NaN,NaN,NaN,NaN,NaN,0.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.198784,0.385943,0.500010,NaN,NaN,NaN,NaN,NaN,0.0
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,0.0
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,0.0
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,0.0
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,0.0
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,0.0

In [62]:
fake=df_na[df_na.fraudulent==1]
fake.describe(include='all')

,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
count,856,856,856,856,856,856,856,856,856.000000,856.000000,856.000000,856,856,856,856,856,856.0
unique,560,374,104,118,50,632,479,308,NaN,NaN,NaN,6,8,11,63,28,NaN
top,Cruise Staff Wanted *URGENT*,"US, TX, Houston",na,na,na,We are a full-service marketing and staffing f...,na,na,NaN,NaN,NaN,Full-time,na,na,na,na,NaN
freq,20,91,524,635,580,22,151,359,NaN,NaN,NaN,487,427,444,270,330,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.074766,0.329439,0.290888,NaN,NaN,NaN,NaN,NaN,1.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.263168,0.470284,0.454437,NaN,NaN,NaN,NaN,NaN,0.0
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,1.0
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,1.0
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,1.0
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,1.0
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,1.0

In [63]:
fake.sample(10)

,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
job_id,,,,,,,,,,,,,,,,,
8596,Clinical Director,"US, VA,",na,na,na,Apply using below link#URL_b76b76a4d2bcc16ce99...,na,na,0,0,0,Full-time,na,na,Hospital & Health Care,na,1
181,Sales Executive,"PK, SD, Karachi",Sales,na,na,Sales Executive,Sales Executive,Sales Executive,0,0,0,na,na,na,na,Sales,1
998,EXECUTIVE SOUS CHEF,"MY, ,",na,55000-65000,Le Meridien is situated in the heart of kuala ...,Responsible for assisting in the direction and...,na,na,0,1,0,Contract,Executive,na,Hospitality,na,1
17533,Typist / Data Processing Clerical,"US, CA, Anaheim",na,na,na,We are seeking individuals to be connected wit...,Home Office SuppliesComputer with internet acc...,na,1,0,0,na,Entry level,Some High School Coursework,na,Administrative,1
17713,Ambulatory Surgery and Endoscopy RN Operations...,"US, CT,",na,na,na,Apply using below link#URL_6b17ba83c57b72435e0...,na,na,0,0,0,Full-time,na,na,Hospital & Health Care,na,1
17573,Home Based Typist (Full/Part Time),"US, NY, New York",na,na,na,Are you looking for a job that allows you to w...,na,USD$1000-2000 per week/USD$ 100.000-120.000per...,0,0,0,na,na,na,na,na,1
17757,Boys & Girls Club,na,na,na,na,Rohan will fill in these projects,na,na,0,0,0,na,na,na,na,na,1
5473,Research Engineer Data Science,"US, CA, San Mateo",Engineering,na,#URL_ddb080358fa5eecf5a67c649cfb4ffc343c484389...,Qualified candidates are encouraged to apply d...,Position requirements: Quickly learning new ar...,Our core values drive our culture. This is wha...,0,1,1,Full-time,Mid-Senior level,Master's Degree,Marketing and Advertising,Engineering,1
17705,Admin Assistant,"US, MI, Grand Rapids",na,na,na,Job DescriptionAdministrative AssistantDescrip...,na,na,0,0,0,Full-time,Entry level,na,Hospital & Health Care,Administrative,1
15931,Software Development engineer,"US, OH, Groveport",na,na,na,Position: Software Development EngineerLocati...,Minimum Qualifications include:A minimum of 7 ...,na,0,0,0,Contract,Mid-Senior level,na,Information Technology and Services,Information Technology,1

In [64]:
fake.loc[17512,:]

title                          Use Your Spare Time to Start Earning More
location                                           US, CA, San Francisco
department                                                            na
salary_range                                                          na
company_profile                                                       na
description            Several people around the world have discovere...
requirements           Professional mannerPositive outlookAbility to ...
benefits               If you have a laptop, phone and a strong desir...
telecommuting                                                          0
has_company_logo                                                       0
has_questions                                                          1
employment_type                                                       na
required_experience                                                   na
required_education                                                    na
industry                                                              na
function                                                              na
fraudulent                                                             1
Name: 17512, dtype: object

In [65]:
fake.loc[3609, :]

title                             Account Sales Managers $80-$130,000/yr
location                                                   US, NY, Utica
department                                                            na
salary_range                                                          na
company_profile        We have aggressive growth plans in place for t...
description            We provide No Credit Check Financing to custom...
requirements           Experience and Skills  Required- Minimum of 3 ...
benefits               We Provide- Complete online training and offic...
telecommuting                                                          0
has_company_logo                                                       1
has_questions                                                          0
employment_type                                                Full-time
required_experience                                            Associate
required_education                             High School or equivalent
industry                                              Financial Services
function                                            Business Development
fraudulent                                                             1
Name: 3609, dtype: object

In [66]:
fake.loc[7655, :]

title                                        Admin Clerk Remote Position
location                                                US, SC, Columbia
department                                                            na
salary_range                                                          na
company_profile                                                       na
description            We are seeking individuals to be connected wit...
requirements           Home Office SuppliesComputer with internet acc...
benefits                                                              na
telecommuting                                                          1
has_company_logo                                                       0
has_questions                                                          0
employment_type                                                       na
required_experience                                          Entry level
required_education                           Some High School Coursework
industry                                                              na
function                                                  Administrative
fraudulent                                                             1
Name: 7655, dtype: object

In [67]:
fake.loc[9843, :]

title                                   Client Services Manager NY, NY 1
location                                                      US, NY, NY
department                                              Client Services
salary_range                                                          na
company_profile        #URL_ddb080358fa5eecf5a67c649cfb4ffc343c484389...
description            #URL_b0c46563ede9cd7db1c4789a59b5459bbd3bc82e0...
requirements           REQUIREMENTSBasic Qualifications:Proven experi...
benefits               Our core values drive our culture. This is wha...
telecommuting                                                          0
has_company_logo                                                       1
has_questions                                                          1
employment_type                                                Full-time
required_experience                                     Mid-Senior level
required_education                                     Bachelor's Degree
industry                                       Marketing and Advertising
function                                                      Consulting
fraudulent                                                             1
Name: 9843, dtype: object

In [68]:
fake.loc[181,:]

title                  Sales Executive
location               PK, SD, Karachi
department                       Sales
salary_range                        na
company_profile                     na
description            Sales Executive
requirements           Sales Executive
benefits               Sales Executive
telecommuting                        0
has_company_logo                     0
has_questions                        0
employment_type                     na
required_experience                 na
required_education                  na
industry                            na
function                         Sales
fraudulent                           1
Name: 181, dtype: object

In [69]:
fake.loc[fake.description=='na']

,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
job_id,,,,,,,,,,,,,,,,,
17514,Office Manager,"PL, MZ, Warsaw",na,na,na,na,na,na,0,0,0,na,na,na,na,na,1

In [70]:
fake.loc[11543, 'description']

"NETGEAR, Inc. (NASDAQGM: NTGR) designs innovative, branded technology solutions that address the specific networking, storage, and security needs of small- to medium-sized businesses and home users. The company offers an end-to-end networking product portfolio to enable users to share Internet access, peripherals, files, multimedia content, and applications among multiple computers and other Internet-enabled devices. Products are built on a variety of proven technologies such as wireless, Ethernet and powerline, with a focus on reliability and ease-of-use. NETGEAR products are sold in over 27,000 retail locations around the globe, and via more than 37,000 value-added resellers. The company's headquarters are in San Jose, Calif., with additional offices in 25 countries.\xa0Director of Engineering | HMA Security ProductsSan Jose, CAReporting to the VP of Service Provider Engineering, the Director of Engineering will have responsibility for managing the successful development and deployment of the company’s Security products and solutions.The individual will manage a focused team of engineers in addition to leading and directing numerous outside technology partners. This includes partnerships with chip set providers, ODMs, new technology start-ups, and 3rd party software providers. As the engineering leader, the individual will work closely with the product marketing team in generating the roadmap of products and solutions that will need to be developed. The Director of Engineering and their team of engineers will then be responsible for determining the best engineering approach to realizing that roadmap, including product architectures, selection of technology partners, resource planning, test planning, product scheduling, costing, and NPI planning. The individual will then manage the team and external partners to ensure the project objectives are met.The Director of Engineering will work closely with customers to get products certified and approved for use.\xa0 Once introduced, the Engineering Manager will work closely with the sales and technical support to ensure customer satisfaction and product quality objectives are being met.\xa0Job ResponsibilitiesAbility to be both a strong Manager and technical leader for the group, with strong domain/forum knowledge of Security products, tables, routers, wireless, and hands-on IP networking experience.\xa0 VoIP experience an advantage.Ideally be known-in and reputable within the networking Industry.10+ years of demonstrable success of strong engineering management background in communications networking hardware and software utilizing Test Driven DevelopmentDemonstrated understanding and skills in project and program management, risk management, including 3rd partiesDemonstrated success in developing products by utilizing outside company resources and partnerships.\xa0 Experience with ODM developments an advantageCan attract, motivate and retain top caliber engineers for the organization.One whom customers and technology partners find credible and look to for direction.5 or more years experience working for a small company, in addition to 5 or more years experience working for a larger more mature market leader.Team player who can effectively work with the cross functional team, and can effectively communicate throughout all levels of the organization.An understanding and desire of how to continuously improve product quality. Demonstrated ability to use lightweight processes to improve engineering results.Can stay on top of and apply the latest technology trends and engineering processes for the organization.\xa0"

In [72]:
na_rates=pd.DataFrame([col, len(real.loc[real[col]=='na'])/len(real[col]), len(fake.loc[fake[col]=='na'])/len(fake[col]) ] for col in df.columns)

In [73]:
na_rates.columns=['column','real_na_rates','fake_na_rates']
na_rates

                 column  real_na_rates  fake_na_rates
0                 title       0.000000       0.000000
1              location       0.019232       0.022196
2            department       0.645285       0.612150
3          salary_range       0.844353       0.741822
4       company_profile       0.161381       0.677570
5           description       0.000000       0.001168
6          requirements       0.149197       0.176402
7              benefits       0.403154       0.419393
8         telecommuting       0.000000       0.000000
9      has_company_logo       0.000000       0.000000
10        has_questions       0.000000       0.000000
11      employment_type       0.190647       0.275701
12  required_experience       0.390312       0.498832
13   required_education       0.451831       0.518692
14             industry       0.272771       0.315421
15             function       0.360330       0.385514
16           fraudulent       0.000000       0.000000

In [74]:
from statsmodels.stats.proportion import proportions_ztest
for col in df.columns:
    counts=np.array([len(real.loc[real[col]=='na']), len(fake.loc[fake[col]=='na'])])
    nobs=np.array([len(real[col]), len(fake[col])])
    if (counts.sum() !=0) and (nobs.sum() !=0):
        na_rates.loc[na_rates.column==col,'zstat'], na_rates.loc[na_rates.column==col,'p_value']=proportions_ztest(count=counts, nobs=nobs,  alternative='two-sided')

In [75]:
na_rates['significant_diff']=na_rates['p_value']<0.005
na_rates

,column,real_na_rates,fake_na_rates,zstat,p_value,significant_diff
0,title,0.000000,0.000000,NaN,NaN,False
1,location,0.019232,0.022196,-0.613697,5.394159e-01,False
2,department,0.645285,0.612150,1.974423,4.833361e-02,False
3,salary_range,0.844353,0.741822,7.968338,1.608222e-15,True
4,company_profile,0.161381,0.677570,-37.819096,0.000000e+00,True
5,description,0.000000,0.001168,-4.422747,9.745384e-06,True
6,requirements,0.149197,0.176402,-2.171139,2.992064e-02,False
7,benefits,0.403154,0.419393,-0.944417,3.449565e-01,False
8,telecommuting,0.000000,0.000000,NaN,NaN,False
9,has_company_logo,0.000000,0.000000,NaN,NaN,False
10,has_questions,0.000000,0.000000,NaN,NaN,False
11,employment_type,0.190647,0.275701,-6.128753,8.857065e-10,True
12,required_experience,0.390312,0.498832,-6.333275,2.400114e-10,True
13,required_education,0.451831,0.518692,-3.831526,1.273510e-04,True
14,industry,0.272771,0.315421,-2.726262,6.405610e-03,False
15,function,0.360330,0.385514,-1.495860,1.346900e-01,False
16,fraudulent,0.000000,0.000000,NaN,NaN,False

In [76]:
df_na['company_profile_length']=df_na.apply(lambda row: len(row.company_profile), axis=1)
df_na['description_length']=df_na.apply(lambda row: len(row.description), axis=1)
df_na['requirements_length']=df_na.apply(lambda row: len(row.requirements), axis=1)
df_na['benefits_length']=df_na.apply(lambda row: len(row.benefits), axis=1)
df_na['total_text_length']=df_na['company_profile_length']+df_na['description_length']+df_na['requirements_length']+df_na['benefits_length']

In [77]:
df_na.head()

,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,...,required_experience,required_education,industry,function,fraudulent,company_profile_length,description_length,requirements_length,benefits_length,total_text_length
job_id,,,,,,,,,,,,,,,,,,,,,
1,Marketing Intern,"US, NY, New York",Marketing,na,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,na,0,1,...,Internship,na,na,Marketing,0,885,905,852,2,2644
2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,na,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,...,Not Applicable,na,Marketing and Advertising,Customer Service,0,1286,2077,1433,1292,6088
3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",na,na,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,na,0,1,...,na,na,na,na,0,879,355,1363,2,2599
4,Account Executive - Washington DC,"US, DC, Washington",Sales,na,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,...,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0,614,2600,1429,782,5425
5,Bill Review Manager,"US, FL, Fort Worth",na,na,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,...,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0,1628,1520,757,21,3926

In [78]:
df_na.industry.value_counts()[:20]

industry
na                                     4837
Information Technology and Services    1711
Computer Software                      1362
Internet                               1054
Education Management                    819
Marketing and Advertising               818
Financial Services                      748
Hospital & Health Care                  483
Consumer Services                       348
Telecommunications                      326
Oil & Energy                            286
Retail                                  223
Real Estate                             166
Accounting                              159
Construction                            152
E-Learning                              138
Design                                  127
Staffing and Recruiting                 127
Management Consulting                   127
Health, Wellness and Fitness            123
Name: count, dtype: int64

In [79]:
fake.industry.value_counts()[:20]

industry
na                                     270
Oil & Energy                           108
Accounting                              57
Hospital & Health Care                  49
Marketing and Advertising               45
Financial Services                      35
Information Technology and Services     32
Telecommunications                      26
Consumer Services                       24
Real Estate                             23
Leisure, Travel & Tourism               20
Health, Wellness and Fitness            15
Hospitality                             14
Computer Networking                     12
Staffing and Recruiting                  8
Insurance                                6
Human Resources                          6
Management Consulting                    6
Computer & Network Security              5
Entertainment                            5
Name: count, dtype: int64

In [80]:
real.industry.value_counts()[:20]

industry
na                                     4567
Information Technology and Services    1679
Computer Software                      1357
Internet                               1054
Education Management                    819
Marketing and Advertising               773
Financial Services                      713
Hospital & Health Care                  434
Consumer Services                       324
Telecommunications                      300
Retail                                  218
Oil & Energy                            178
Construction                            149
Real Estate                             143
E-Learning                              136
Design                                  123
Management Consulting                   121
Staffing and Recruiting                 119
Insurance                               115
Automotive                              112
Name: count, dtype: int64

In [81]:
industry=pd.crosstab(df_na.industry, df_na.fraudulent, normalize='index', margins=True)
industry.iloc[:,1].sort_values(ascending=False)[:20].to_frame(name='fraud rates')

                                      fraud rates
industry
Ranching                                 1.000000
Military                                 0.500000
Animation                                0.400000
Oil & Energy                             0.377622
Accounting                               0.358491
Computer Networking                      0.279070
Leisure, Travel & Tourism                0.277778
Executive Office                         0.250000
Defense & Space                          0.222222
Business Supplies and Equipment          0.166667
Investment Management                    0.166667
Hospitality                              0.159091
Public Safety                            0.142857
Real Estate                              0.138554
Health, Wellness and Fitness             0.121951
Civil Engineering                        0.111111
Mechanical or Industrial Engineering     0.108108
Biotechnology                            0.105263
Computer & Network Security              0.104167
Hospital & Health Care                   0.101449

In [82]:
df_na.title.value_counts()[:20]

title
English Teacher Abroad                                309
Graduates: English Teacher Abroad (Conversational)    144
Customer Service Associate                            141
English Teacher Abroad                                 94
Software Engineer                                      86
English Teacher Abroad (Conversational)                83
Account Manager                                        74
Customer Service Associate - Part Time                 72
Web Developer                                          65
Project Manager                                        60
Graduates: English Teacher Abroad                      57
Beauty & Fragrance consultants needed                  55
Customer Service Representative                        51
Administrative Assistant                               47
Office Manager                                         46
Product Manager                                        46
Marketing Manager                                      45
Web Designer                                           44
Senior Software Engineer                               44
Sales Representative                                   43
Name: count, dtype: int64

In [83]:
fake.title.str.contains('$', regex=False).value_counts(normalize=True)

title
False    0.932243
True     0.067757
Name: proportion, dtype: float64

In [84]:
real.title.str.contains('$', regex=False).value_counts(normalize=True)

title
False    0.995759
True     0.004241
Name: proportion, dtype: float64

In [85]:
df_na.location.value_counts()[:20]

location
GB, LND, London          718
US, NY, New York         644
US, CA, San Francisco    466
GR, I, Athens            462
na                       341
US, ,                    339
US, TX, Houston          265
US, IL, Chicago          249
US, DC, Washington       249
DE, BE, Berlin           221
NZ, N, Auckland          217
US, CA, Los Angeles      180
GB, , London             177
US, TX, Austin           173
US, CA, San Diego        162
GB, ,                    138
GB, LND,                 131
US, GA, Atlanta          129
US, OR, Portland         128
CA, ON, Toronto          119
Name: count, dtype: int64

In [86]:
fake.location.value_counts()[:20]

location
US, TX, Houston          91
AU, NSW, Sydney          30
US, ,                    28
US, CA, Bakersfield      24
US, CA, Los Angeles      23
US, CA, San Mateo        22
US, NY, New York         20
na                       19
US, TX, AUSTIN           14
US, CA, San Jose         14
US, TX, DALLAS           11
US, MD, Baltimore        11
US, CA, San Francisco    11
US, CA,                   9
US, OH, Cincinnati        8
US, NY, NY                8
MY, ,                     7
US, TX, Austin            7
US, CA, LOS ANGELES       6
CA, ON, Toronto           6
Name: count, dtype: int64

In [87]:
df.location=df.location.str[:2]

In [88]:
df.location.value_counts()

location
US    10460
GB     2329
GR      938
CA      450
DE      382
      ...
SI        1
PE        1
SD        1
UG        1
KH        1
Name: count, Length: 90, dtype: int64

In [89]:
real.location=real.location.str[:2]
real.location.value_counts(normalize=True).head(10)

<ipython-input-89-2152d1c20c3d>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  real.location=real.location.str[:2]

location
US    0.581676
GB    0.137729
GR    0.056023
CA    0.026160
DE    0.022816
NZ    0.019710
na    0.019232
IN    0.016066
AU    0.010392
PH    0.007824
Name: proportion, dtype: float64

In [90]:
fake.location=fake.location.str[:2]
fake.location.value_counts(normalize=True).head(10)

<ipython-input-90-57c9d53b9886>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fake.location=fake.location.str[:2]

location
US    0.842290
AU    0.045561
GB    0.026869
na    0.022196
MY    0.014019
CA    0.014019
QA    0.007009
BH    0.005841
IN    0.004673
PL    0.003505
Name: proportion, dtype: float64

In [91]:
df.salary_range.value_counts()

salary_range
0-0            141
40000-50000     66
30000-40000     54
45000-67000     36
25000-30000     36
              ...
60-75            1
27500-36000      1
20-22            1
110-120          1
3700-3800        1
Name: count, Length: 874, dtype: int64

In [92]:
real.salary_range.value_counts(normalize=True)

salary_range
na               0.844353
0-0              0.008183
40000-50000      0.003882
30000-40000      0.002986
45000-67000      0.002150
                   ...
300000-325000    0.000060
27500-36000      0.000060
20-22            0.000060
110-120          0.000060
15500-16500      0.000060
Name: proportion, Length: 829, dtype: float64

In [93]:
fake.salary_range.value_counts(normalize=True)

salary_range
na                 0.741822
7200-1380000       0.011682
30000-50000        0.009346
250000-500000      0.008178
28000-32000        0.007009
                     ...
34000-50000        0.001168
2000-2000          0.001168
6266624-8582080    0.001168
30000-100000       0.001168
0-30000            0.001168
Name: proportion, Length: 118, dtype: float64

In [94]:
real_text=real.title+' '+real.company_profile+' '+real.description+' '+real.requirements+' '+real.benefits

In [95]:
real_text_frame=real_text.to_frame(name='text')
fake_text=fake.title+' '+fake.company_profile+' '+fake.description+' '+fake.requirements+' '+fake.benefits
fake_text_frame=fake_text.to_frame(name='text')

In [96]:
real_text.str.contains('#URL', regex=False).value_counts(normalize=True)

False    0.684346
True     0.315654
Name: proportion, dtype: float64

In [97]:
fake_text.str.contains('#URL', regex=False).value_counts(normalize=True)

False    0.690421
True     0.309579
Name: proportion, dtype: float64

In [98]:
fake_text.str.contains('#EMAIL', regex=False).value_counts(normalize=True)

False    0.799065
True     0.200935
Name: proportion, dtype: float64

In [99]:
real_text.str.contains('#EMAIL', regex=False).value_counts(normalize=True)

False    0.931733
True     0.068267
Name: proportion, dtype: float64

In [100]:
fake_text.str.contains('#PHONE', regex=False).value_counts(normalize=True)

False    0.90771
True     0.09229
Name: proportion, dtype: float64

In [101]:
real_text.str.contains('#PHONE', regex=False).value_counts(normalize=True)

False    0.9739
True     0.0261
Name: proportion, dtype: float64

In [102]:
fake_text[9835]

"Director of Product Management #URL_ddb080358fa5eecf5a67c649cfb4ffc343c484389f1bbaf2a1cb071e3f2b6e7e# and Aptitude Staffing Solutions have partnered up in an effort to streamline the hiring process and provide a more efficient and effective recruitng model.\xa0 Our focus is to help develop and achieve your career goals while makeing a solid geographical, cultural and professional fiit when leveraging your career into your new and exciting professional venture!Please direct all communications throughout this process to the HR department at Aptitude Staffing Solutions#EMAIL_0c020555b4dbc1c1e03d03c46cc181bcfde81bf5b20fea95d1bc7dc64c79814c#Darren Lawson | VP of Recruiting | #EMAIL_f4da338e899ddba983ac771b001681d1d2d93b3327ddc420a15f4e5a310071a9#\xa0| #PHONE_90d33c9d7ec1484aebfe37b153d677decc6f5f53b316489ed24061544c04eb66# Director, Product Management | San Mateo, CASan Mateo, CA, United States Seeking a talented and experienced Director of Product Management to lead the design of key components of an advanced platform for video advertising. Great for a senior product leader who thrives off chalenges, builds industry-changing products, and can lead a team. The product team is a small group of smart, creative, and disciplined professionals that are eager to master challenging projects and respond well to mentorship and are accustomed to operating under a lean startup environment and practice lean software development. We labor over every product prioritization decision, and we believe in building minimal viable products. Build, measure and learn!Job Responsibilities:Build expertise of the current structure and dynamics of the digital video advertising industry, and develop a point of view about market trends and emerging opportunities.Meet frequently with customers, potential customers, and partners - to develop a deep understanding of their current business processes and product needs.Develop a comprehensive vision and roadmap for product, or suite of products. Build alignment among internal and external stakeholders around this vision. Set aggressive goals for execution, and chart progress.Lead your team of product managers to develop designs that address needs and requirements expressed by internal and external customers. Designs should be simple, minimal, extensible, consistent with existing functionality, and easy to use. \xa0Work with UX designers and engineers to continuously deliver new functionality, in a way that is seamlessly integrated into robust infrastructure and a beautiful user interface.Attract, hire, inspire, and grow a team of superstar product managers.\xa0\xa0 Job Requirements:Must be able to demonstrate and/or describe a substantial software product that you built personally, either on the job or as a personal project, demonstrating your ability to envision, define, and execute independently.5-10 years working as product manager, including 2+ years as a senior product lead on a large-scale web application or enterprise software product with front and back-end processes.Deep knowledge of user experience principles, and experience applying them to build usable user experiencesDeep knowledge of application design principles, including object modeling, extensibility, SOA, etc., and experience applying them to build complex software applicationsProven and continued success collaborating with cross-functional groups including corporate management, engineering, client services, enterprise customers, and direct sales teams.Exceptional and demonstrable problem-solving and design capabilities.Experience with online advertising preferred, but not required.Strong technical aptitude: BS or MS in technical field from top university. Computer science degree preferred.MBA welcomed but not required. Our core values drive our culture. This is what we believe: Why #URL_ddb080358fa5eecf5a67c649cfb4ffc343c484389f1bbaf2a1cb071e3f2b6e7e#? Watch our culture video to learn more.MAKE OUR CUSTOMERS SUCCESSFUL Our customers' success is ours. We live to solve their problems, improve their futures, and exceed their expectations. When our customers win, we win.SET THE BAR HIGH. We're trying to revolutionize an industry, so we can't be just good—we have to be the best. That means striving for the best team, product, and company on the planet.BE ACCOUNTABLE. We own our work. We keep our promises. And we always follow through. We take responsibility for failures, and humble bows for successes. There's no time for excuses and finger pointing.SHOW INTEGRITY. Forget loopholes, back doors, and shades of gray. We just say it. We are honest and straightforward with everyone. The only way we can bring clarity to a chaotic world is to walk-the-walk ourselves.MAKE EACH OTHER BETTER. Everything we achieve, we achieve together. Nobody is too important to grab a broom.ALWAYS MOVE FORWARD. We see the world as it could be, not just as it is. With our passion for finding new solutions to old problems, we're creating that new world. It's a future worth adapting to.The Benefits Generous paid time off to help you maintain a good work-life balanceFully catered lunches available everyday to all employees at the corporate officeOffices fully stocked with snacks and refreshments to keep you energized and productiveExtensive employee benefits and perks to show how much we value your effortsFun team events, company events, employee sponsored events, employee recognition awards, and more!\xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0 \xa0"